name: CI4

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a multi-line script
        id: v1
        run: git_hash=$(git rev-parse --short "$GITHUB_SHA")
      - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: print commit id
        run: echo ${{steps.v1.git_hash}}
      - name: build
        run: docker build -t 8485012281/webserver:${{steps.v1.git_hash}}
      - name: push
        run: docker push 8485012281/webserver:${{steps.v1.git_hash}}
       - name: Run
        run: docker run -d --name mycontainer -p 8888:8888 8485012281/webserver
      - name: Run
        run: docker ps
      - name: sleep
        run: sleep 30
      
      - name: curl
        run: curl localhost:8888  
